# ----- Ameliorate Token <AmeliorateGame.com> -----
# ----- Visit us at the Official Ameliorate Game Blog <Ameliorate.Game.Blog> -----

NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
VERSION = "2.5.0"
SIGNING_KEY = "GDU2P2VOKVXRFEPGSGQE5X4B3IO526TOL3ZL7JTMACH5X2SFGDQFEWIQ"
ACCOUNTS = [
    "GAI4UZHPC7VSBQ77IMJWVAOPGOJIVCSP2BBI3BX2FBLUPIXVONXIMF5G",
    "GDU2P2VOKVXRFEPGSGQE5X4B3IO526TOL3ZL7JTMACH5X2SFGDQFEWIQ",
]

[DOCUMENTATION]
ORG_NAME = "Ameliorate Game"
ORG_URL = "https://AmeliorateGame.com"
ORG_LOGO = "https://ameliorategame.com/img/Ameliorate%20Logo%20-%20128x128.png"
ORG_DESCRIPTION = "An epic web3 RPG powered by Stellar and taking place in Discord and our Web App. Buy, Sell, and exchange items to make yourself powerful.   Acquire, Grow, and Conquer lands to Build an empire."
ORG_TWITTER = "@AmeliorateGame"
ORG_GITHUB  =  "Psylocybin42"
ORG_KEYBASE = "ameliorategame"
ORG_OFFICIAL_EMAIL = "support@AmeliorateGame.com"

[[PRINCIPALS]]
name = "Psylocybin42"
email = "Psylocybin42@gmail.com"
keybase = "Psylocybin42"
twitter = "@Psylocybin42"
github = "Psylocybin42"



# ----- Ameliorate Token -----
# ----- Below is the Ameliorate Token for the entire Ameliorate Project -----
[[CURRENCIES]]
code = "Ameliorate"
issuer = "GAI4UZHPC7VSBQ77IMJWVAOPGOJIVCSP2BBI3BX2FBLUPIXVONXIMF5G"
display_decimals = 2
status = "live"
is_asset_anchored = false
name = "Ameliorate Token"
desc = "An epic web3 RPG powered by Stellar and taking place in Discord and our Web App. Buy, Sell, and exchange items to make yourself powerful.   Acquire, Grow, and Conquer lands to Build an empire."
conditions = "There will only be 42,000,000 Ameliorate Tokens in existence."
image = "https://bafkreib62zqcf3cvamvy3hksak6xdnl2dm5mufktll7ew55t2qpwdwtg5q.ipfs.nftstorage.link/"
fixed_number = 42000000




# ----- Ameliorate Game Assets -----
# ----- Below are the In-Game Assets (NFTs) for the Ameliorate Game  -----

# ----- Ameliorate Metalic Coins -----
[[CURRENCIES]]
code = "PlatinumCoin"
issuer = "GAI4UZHPC7VSBQ77IMJWVAOPGOJIVCSP2BBI3BX2FBLUPIXVONXIMF5G"
display_decimals = 2
status = "live"
is_asset_anchored = false
name = "Platinum Coins"
desc = "Ameliorate Game Platinum Coins"
conditions = "There will only be 1,000,000 Ameliorate Platinum Coins in existence."
image = "https://ameliorategame.com/img/Ameliorate%20Logo%20-%20128x128.png"
fixed_number = 1000000

[[CURRENCIES]]
code = "GoldCoin"
issuer = "GAI4UZHPC7VSBQ77IMJWVAOPGOJIVCSP2BBI3BX2FBLUPIXVONXIMF5G"
display_decimals = 2
status = "live"
is_asset_anchored = false
name = "Gold Coins"
desc = "Ameliorate Game Gold Coins"
conditions = "There will only be 100,000,000 Ameliorate Gold Coins in existence."
image = "https://ameliorategame.com/img/Ameliorate%20Logo%20-%20128x128.png"
fixed_number = 100000000

[[CURRENCIES]]
code = "SilverCoin"
issuer = "GAI4UZHPC7VSBQ77IMJWVAOPGOJIVCSP2BBI3BX2FBLUPIXVONXIMF5G"
display_decimals = 2
status = "live"
is_asset_anchored = false
name = "Silver Coins"
desc = "Ameliorate Game Silver Coins"
conditions = "There will only be 10,000,000,000 Ameliorate Silver Coins in existence."
image = "https://ameliorategame.com/img/Ameliorate%20Logo%20-%20128x128.png"
fixed_number = 10000000000

[[CURRENCIES]]
code = "CopperCoin"
issuer = "GAI4UZHPC7VSBQ77IMJWVAOPGOJIVCSP2BBI3BX2FBLUPIXVONXIMF5G"
display_decimals = 2
status = "live"
is_asset_anchored = false
name = "Copper Coins"
desc = "Ameliorate Game Copper Coins"
conditions = "There will only be 100,000,000,000 Ameliorate Copper Coins in existence."
image = "https://ameliorategame.com/img/Ameliorate%20Logo%20-%20128x128.png"
fixed_number = 100000000000


# ----- Ameliorate Lands -----
